name: Node CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x]
    steps:
      - name: Check out repository
        uses: actions/checkout@v1
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NPM Dependencies
        run: npm install
      - name: Lint
        run: npm run lint --if-present
      - name: Build for Node.js
        run: npm run build-node --if-present
      - name: Build for Web
        run: npm run build-web --if-present
      - name: Run Jest Tests
        run: npm test
        env:
          CI: true
